Repository foyzulkarim/mern-video-streaming, pull requests merged in 2023-08, with the labels that each got.

#60 Implement seed data mechanism for Role collection
  server/scripts/seed-data/role.js
Labels: reviewed

#47 update video status to published when processing is finished
  client/package.json
  client/src/pages/ProductsPage.js
  client/src/pages/VideosPage.js
  client/src/sections/@dashboard/products/ProductList.js
  client/src/sections/@dashboard/products/VideoCard.js
  client/src/sections/@dashboard/products/VideoList.js
  client/src/sections/@dashboard/products/index.js
  client/yarn.lock
  server/package-lock.json
  server/package.json
  server/scripts/seed-data/video.js
  server/src/modules/db/constant.js
  server/src/modules/db/schemas/videos.js
  server/src/modules/models/video/controller.js
  server/src/modules/models/video/handler.js
  server/src/modules/models/video/service.js
  server/src/modules/queues/video-processor.js
Labels: ready for review

#62 Show video thumbnail
  server/src/modules/db/schemas/videos.js
  server/src/modules/models/video/service.js
Labels: bug

#63 Deploy static content to Pages
  .github/workflows/static.yml
Labels: ongoing

#66 Fix yarn build
  .github/workflows/static.yml
  client/src/pages/VideoListPage.js
  client/src/pages/VideoPlayerPage.js
  client/src/pages/VideoUploadPage.js
Labels: bug

#59 Implemented generic `deleteById`
  server/src/modules/db/collections.js
  server/src/modules/models/video/request.js
  server/src/modules/models/video/service.js
Labels: reviewed

#69 Modify `init-directories` script for supporting MacOs
  server/scripts/shell-script.mjs
Labels: bug

#77 Update `README` for running docker command
  README.md
  server/Dockerfile
  server/src/modules/models/video/controller.js
  server/src/modules/models/video/service.js
Labels: bug, task

#78 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#79 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#81 Videos searching sorting pagination in the list page
  client/package.json
  client/src/pages/VideoListPage.js
  client/yarn.lock
  server/src/modules/db/collections.js
  server/src/modules/db/schemas/videos.js
  server/src/modules/models/video/controller.js
  server/src/modules/models/video/service.js
Labels: task

#82 video edit page
  client/src/pages/VideoEditPage.js
  client/src/pages/VideoListPage.js
  client/src/pages/VideoPlayerPage.js
  client/src/routes.js
  server/src/modules/models/video/controller.js
  server/src/modules/models/video/request.js
Labels: task
